name: email_password_login
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  http: ^0.13.4
  bubble: ^1.2.1
  flutter_spinkit: ^5.1.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
   

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Logo-removebg-preview (2).png
    - assets/Logo.png
    - assets/background.jpg
    - assets/Anxiety.png
    - assets/LungCancer.png
    - assets/BreastCancer.jpg
    - assets/Mood-Disorders.jpg
    - assets/OCD.jpg
    - assets/psychotic_disorders.jpg
    - assets/PTSD.jpg
    - assets/KidneyCancer.png
    - assets/Malaria.jpg
    - assets/Account.png
    - jsonfile/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
   - family: Yuji
     fonts:
       - asset: fonts/YujiSyuku-Regular.ttf
         weight: 300

   - family: Ceviche
     fonts:
       - asset: fonts/CevicheOne-Regular.ttf

   - family: Balsamiq
     fonts:
       - asset: fonts/BalsamiqSans-Regular.ttf

   - family: BreeSerif
     fonts:
       - asset: fonts/BreeSerif-Regular.ttf

   - family: Carter
     fonts:
        - asset: fonts/CarterOne-Regular.ttf

   - family: Sniglet
     fonts:
        - asset: fonts/Sniglet-Regular.ttf

   - family: RalewayR
     fonts:
         - asset: fonts/Raleway-VariableFont_wght.ttf

   - family: RalewayI
     fonts:
         - asset: fonts/Raleway-Italic-VariableFont_wght.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
